# Generated by Django 4.0.5 on 2023-07-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_vehiculopermission_alter_vehiculo_condicion_precio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculopermission',
            options={'verbose_name': 'visualizar_catalogo', 'verbose_name_plural': 'Permisos para visualizar Catálogo de Vehículos'},
        ),
    ]
