# Generated by Django 4.0.5 on 2023-07-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0005_alter_vehiculopermission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculopermission',
            options={'verbose_name': 'visualizar_catalogo', 'verbose_name_plural': 'Permisos para visualizar Catálogo de Vehículos'},
        ),
    ]
